version: "3"

services:
  indexer:
    image: postgres

  storage:
    image: redis

  gnocchi-metricd:
    image: gnocchi
    environment:
      POSTGRESQL_USER: postgres
    build:
      context: gnocchi
      args:
        package_name: "${GNOCCHI_PACKAGE_NAME:-gnocchi}"
    depends_on:
      - indexer
      - storage
    volumes:
      - metrics-volume:/var/lib/gnocchi
    entrypoint: /run-gnocchi.sh metricd

  gnocchi-api:
    image: gnocchi
    environment:
      POSTGRESQL_USER: postgres
    build:
      context: gnocchi
      args:
        package_name: "${GNOCCHI_PACKAGE_NAME:-gnocchi}"
    ports:
      - "8041:8041"
    depends_on:
      - indexer
      - storage
      - gnocchi-metricd
    volumes:
      - metrics-volume:/var/lib/gnocchi
    entrypoint: /run-gnocchi.sh api

  grafana:
    image: gnocchixyz/grafana
    build:
      context: grafana
    environment:
      - GNOCCHI_RATE_SUPPORT
      - GRAFANA_PLUGIN_URL
      # - GF_INSTALL_PLUGINS=gnocchixyz-gnocchi-datasource
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_GNOCCHI_ENDPOINT=http://gnocchi:8041
    ports:
      - "3000:3000"
    depends_on:
      - gnocchi-api
    volumes:
      - grafana-volume:/var/lib/grafana
    links:
      - "gnocchi-api:gnocchi"

  fake-phy-host:
    image: collectd
    build:
      context: collectd
      args:
        package_name: "${COLLECTD_GNOCCHI_PACKAGE_NAME:-collectd-gnocchi}"
    environment:
      COLLECTD_INTERVAL: 10
    depends_on:
      - gnocchi-api
    links:
      - "gnocchi-api:gnocchi"

volumes:
  metrics-volume:
  grafana-volume:
